package com.example.clothingretailer;

import android.content.Context;

public class TestGenerator {
    public static void generate_test_db(Context context)
    {
        DBHandler handler = new DBHandler(context);

        // fill user table
        /*handler.add_user("username1", "password1", "firstname1", "lastname1", User.MALE, "email1", "phone1", "birthday1", "address1");
        handler.add_user("username2", "password2", "firstname2", "lastname2", User.MALE, "email2", "phone2", "birthday2", "address2");
        handler.add_user("username3", "password3", "firstname3", "lastname3", User.MALE, "email3", "phone3", "birthday3", "address3");
        handler.add_user("username4", "password4", "firstname4", "lastname4", User.MALE, "email4", "phone4", "birthday4", "address4");
        handler.add_user("username5", "password5", "firstname5", "lastname5", User.MALE, "email5", "phone5", "birthday5", "address5");
        handler.add_user("username6", "password6", "firstname6", "lastname6", User.FEMALE, "email6", "phone6", "birthday6", "address6");
        handler.add_user("username7", "password7", "firstname7", "lastname7", User.FEMALE, "email7", "phone7", "birthday7", "address7");
        handler.add_user("username8", "password8", "firstname8", "lastname8", User.FEMALE, "email8", "phone8", "birthday8", "address8");
        handler.add_user("username9", "password9", "firstname9", "lastname9", User.FEMALE, "email9", "phone9", "birthday9", "address9");

        // fill item table
        handler.add_item("itemname1", Item.MALE, "t-shirt", "dt1", "d1", "ht1", "h1", "link1", 1);
        handler.add_item("itemname2", Item.MALE, "type2", "dt2", "d2", "ht2", "h2", "path2", 2);
        handler.add_item("itemname3", Item.MALE, "type3", "dt3", "d3", "ht3", "h3", "path3", 3);
        handler.add_item("itemname4", Item.MALE, "type4", "dt4", "d4", "ht4", "h4", "path4", 4);
        handler.add_item("itemname5", Item.MALE, "type5", "dt5", "d5", "ht5", "h5", "path5", 5);
        handler.add_item("itemname6", Item.MALE, "type6", "dt6", "d6", "ht6", "h6", "path6", 6);
        handler.add_item("itemname7", Item.MALE, "type7", "dt7", "d7", "ht7", "h7", "path7", 7);
        handler.add_item("itemname8", Item.MALE, "type8", "dt8", "d8", "ht8", "h8", "path8", 8);
        handler.add_item("itemname9", Item.MALE, "type9", "dt9", "d9", "ht9", "h9", "path9", 9);
        // Shorts
        handler.add_item("Men's 7\" breathable sports short", Item.MALE, "shorts", "Breathable 7\" Recycle Men's Sports Shorts", "BespokeTailor has introduced a variety of sports products made from various materials, including Maxcool, Poly Quickdry, and... Following on from previous sports products and the garment industry trend of \"sustainable fashion\", BespokeTailor launched Product eyes 7\" Recycle men's sports pants that are environmentally friendly, with the main ingredient being 100% Recycled yarn.","HIGHLIGHTS", "- Fabric: 100% recycled yarn that adheres to sustainable fashion trends.\n- Advantages: Longevity, less wrinkles, and good form retention.\n- Quickdry (quick drying) + Wicking (fast absorbing) + Stretch are the application technologies (Stretch).\n-Sporty design with the ideal length for all sports activities\n- The belt has an elastic band that allows guys to adjust the elasticity, making it suitable for the waistline.\n- 7 inch pants length suitable for sports activities such as running, sports, etc.\n- Wicking technology (Quick Absorption) provides many outstanding features: cooling and breathability ", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_1.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_3.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_2.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_7.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_4.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_5.jpg",239000);
        handler.add_item("New French Terry V2 Men's Shorts (embroidered logo)", Item.MALE, "shorts","Product details","New French Terry Shorts men's pants combine with CVC weave - a weave that creates more air between the fibers to give you a more airy and cooler wearing experience, we want your activities to be comfortable. more convenient, easier and faster, even if it's just everyday activities, so simple that no one wants to care.", "HIGHLIGHTS", "- Lighter: help men always feel comfortable and confident when wearing pants on their body\n- Breathable: does not leave an unpleasant smell after a long day of exercise\n- Absorbency: maximum perspiration absorption\n- Stretch: 4-way stretch is always comfortable when moving.\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/terry_shorts_xam_1.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/terry_shorts_xam_2.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/terry_shorts_xam_3.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/terry_shorts_xam_4.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/134-4.jpg", 250000);
        handler.add_item("5\" New Ultra Men's Sports Shorts (with split hem & back zip pocket)", Item.MALE, "shorts", "Design Men's Sports Shorts 5\" New Ultra", "We has designed the best for men's shorts, providing the most comfortable and convenient men's shorts:\n- Elastic waistband and internal drawstring for convenient fit adjustment.\n- The back pocket has a convenient YKK zipper, along with 2 side pockets for convenient personal belongings.\n- Split hem is convenient for all activities with logo design for sportiness.\n", "HIGHLIGHTS", "- Suitable for: sports activities\n- Application technology: Quick Dry (quick drying) + Wicking (fast absorbing) + Stretch (Stretch)\n- Vải được cung từ Promax, công ty vải hàng đầu thế giới trong lĩnh vực thể thao.\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01225-copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01238-copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01253-copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01259-copy_65.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01503-copy-den.jpg",  189000);
        handler.add_item("7\" Stretch Nylon Outdoor Shorts (with back pocket)", Item.MALE, "shorts", "Product details", "With a basic design that is suitable for all shapes of men who are currently aiming for and very fond of:\n- Elastic waistband with drawstring outside, easy to adjust to fit around the waist\n- YKK zipper pockets along the sides of the pants, Lifetime warranty by Coolmate\n- There is an extra pocket on the back, easy and convenient to fit your wallet, iphone promax and above\n", "HIGHLIGHTS", "- Suitable for: picnics, experiences or intense activities\n- Pants length: 7 inches\n- Durable\n- Much cooler than polyester fabric\n- Good stretch\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23_2.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23_3.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23_1.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23_4.jpg", 289000);
        handler.add_item("Movement 7\" stretch men's sports shorts", Item.MALE, "shorts", "Product details", "- Ultra-light fabric is only 106 gsm, giving the feeling of wearing nothing\n- Fabric finishing technology makes the pants comfortable, dry and comfortable for light running and gym activities\n- Double Weaving weave gives a Cooling feeling to wear.\n- Mix in Sporty/Athleisure style with a tank top with sports shoes and running shoes\n- Mix in a casual style with T-shirts, polo shirts.\n", "HIGHLIGHTS", "- With an ultra-lightweight fabric of only 106 gsm, it feels like you're not wearing it\n- The fabric is dyed with Zero Water Discharge technology to pursue the trend of sustainable fashion elements\n- Quick-wicking, 4-way stretch and quick-drying fabric.\n- Suit for: wear light running sports or gym.\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/DSC01693-copyxam7_36.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/DSC00679_copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/DSC00690_copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/DSC00695_copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/DSC00721_copy.jpg", 239000);
        handler.add_item("Breathable ProMax-S1 Men's Sports Shorts", Item.MALE, "shorts", "Product details", "Feel the softness and smoothness at the first touch. And just wearing experience, you will definitely like and always choose this high-quality shorts every day.\n    Coolmate is sure that you will want to choose pants to not only feel comfortable but also individual items to make you more beautiful, making people look at you and say \"You look so good in these pants!\"\n This is also the material used by Coolmate in the line of sports polo shirts and has received a lot of positive feedback and love from customers. Surely Promax-S1 Men's Sports Shorts will also give you the most comfort and effective movement.\n", "HIGHLIGHTS", "- Advantages: Cool, breathable, deodorant.\n- Application technology: Quickdry (quick drying) and Wicking (absorbent)\n- Suit for: wear at home.\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/_MG_0190_(1).jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC05891-copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/thumb_quan_promax_den.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/April2022/quanpromax_7.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/April2022/quanpromax_8.jpg", 189000);
        handler.add_item("Taydey Metallic Shorts for Women Hot Sparkly Shiny Shorts with Elastic Drawstring", Item.FEMALE, "shorts","Product Details","- Fashion and Sports Outfit: Metallic Sparkly Shorts are perfect for fantastic 80's themed parties,yoga,disco,workout,exercise,fitness,dance,clubs,night out,cosplay,hallowen costumes,carnival,christmas,new year party, make you attractive during the activity.\n Functional Design: These shiny metallic shorts, featured with practical side pockets, will offer you comfortable wearing experience as well as stylish look. Get ready for festivals in these stunning rave shorts.\n- Sexy bright colors: Silver Shorts,Gold Shorts,Green Shorts,Blue Shorts,Purple Shorts,Black Shorts,Pink Shorts,Red Shorts,Multicolor Silver Shorts,Teal Shorts,any of them is perfect for your party day\n", "HIGHLIGHTS", "- Imported\n- Drawstring closure\n- Material for hot shiny shorts: 100% Polyester.Shiny ,Skin-friendly, breathable, lightweight, soft and comfortable touch.\n- Main Feature for metallic shorts: Inspired by the traditional dolphin hem shorts,our metallic short for woman is equipped with an elastic waist and adjustable drawstring in the front, offering a loose and flattering fit.\n- 100% Polyester", "https://m.media-amazon.com/images/I/81YPKVhLcvL._AC_UX522_.jpg<<<https://m.media-amazon.com/images/I/81ft+pyEPLL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/81UeGcXxHgL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71LmL0j2b7L._AC_UY550_.jpg",300000);
        handler.add_item("Mounblun Women's Yoga Lounge Shorts Hiking Active Running Workout Shorts Comfy Travel Casual Shorts with Pockets", Item.FEMALE, "shorts", "Product Details", "- Sweat shorts are perfect for yoga, running, travel, hiking, workout, walking or daily wear. They're light, cool, breathable and stretchy, making it a great summer short for vacation\n- Two sides hand pockets to hold small essentials like a key, card or cash etc; Comfy, wide waistband stays put to ensure all-day comfort; Adjustable drawcord for a custom fit.\n", "HIGHLIGHTS", "- Excellent Flatlock stitching reduces chafing, provide next-to-skin softness and chafe-free comfort.\n- Drawstring closure\n- Imported.\n", "https://m.media-amazon.com/images/I/61tPojEhMlL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/61+SuQtUlbL._AC_UX522_.jpg<<<https://m.media-amazon.com/images/I/51OIzyNC6cL._AC_UY550_.jpg",350000);
        handler.add_item("Women's Mid-Rise 7\" (approx. 18cm) Biker Shorts", Item.FEMALE,"shorts", "Product Details", "Train like a pro and crush your goals. The soft, stretchy fabric of these biker shorts hugs your body for gentle support, while sweat-wicking technology helps you stay dry when you're pushing through your final set.\n\nSweat-Wicking Power\nNike Dri-FIT Technology moves sweat away from your skin for quicker evaporation, helping you stay dry and comfortable.\n\nFuturistic Style\nBright neon linear graphics map the body and frame the hips for a strong, futuristic look.", "HIGHLIGHTS", "- 78–83% polyester/18–22% elastane.\n- Material percentage may vary. Check label for actual content.\n- 18cm (approx.) inseam\n- Mid-rise waistband\n", "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/efb14c3c-ca1a-4adc-b6e2-9d76ca5d9d32/pro-mid-rise-7-biker-shorts-5cqF51.png<<<https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/648292a7-ef9b-43cd-8f7e-e35e23216f51/pro-mid-rise-7-biker-shorts-5cqF51.png<<<https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/efb14c3c-ca1a-4adc-b6e2-9d76ca5d9d32/pro-mid-rise-7-biker-shorts-5cqF51.png", 500000);

// Sweater

        handler.add_item("Essentials Men's Crewneck Sweater", Item.MALE, "sweaters", "PRODUCT DETAILS", "- Black solid pullover sweater, has a V-neck, long sleeves, and ribbed hem\n- Material: Acrylic\n- Machine Wash\n", "HIGHLIGHTS", "- 100% Cotton\n- Machine Wash\n- This casual wardrobe-essential comes in a lightweight fabric perfect for comfortable everyday wear\n- Features ribbing on the collar, hem, and cuffs to keep you warm\n- Everyday made better: we listen to customer feedback and fine-tune every detail to ensure quality, fit, and comfort\n", "https://m.media-amazon.com/images/I/91nG7tYFJ4L._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/91Z-b-OtcgL._AC_SY550._SX._UX._SY._UY_.jpg<<<https://m.media-amazon.com/images/I/81+SpBJGOuL._AC_UX522_.jpg<<<https://m.media-amazon.com/images/I/81PDMaQeDVL._AC_SY550._SX._UX._SY._UY_.jpg", 500000);
        handler.add_item("Essentials Men's Full-Zip Cotton Sweater", Item.MALE, "sweaters", "PRODUCT DETAILS", " Our line of men’s must-haves includes polo shirts, chino pants, classic-fit shorts, casual button-downs, and crew-neck tees. Our consistent sizing takes the guesswork out of shopping, and each piece is put to the test to maintain the highest standards in quality and comfort", "HIGHLIGHTS", "- 100% Cotton\n- Machine Wash\n- This cotton sweater is perfect on its own or as a layer under a blazer or jacket\n- Full-zip front, with side pockets and ribbing at the cuffs and hem\n- Everyday made better: we listen to customer feedback and fine-tune every detail to ensure quality, fit, and comfort\n","https://m.media-amazon.com/images/I/71mW2Bu61HL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/811968h0yxL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71IHaAVOISL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81dbTeXisPL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/61FJbEsliDL._AC_UY550_.jpg", 600000);
        handler.add_item("IZOD Men's Premium Essentials Solid V-Neck 12 Gauge Sweater", Item.MALE,"sweaters", "PRODUCT DETAILS", "This classic men's V-neck sweater adds a dose of ivy league style to any look. With a logo-free design for a clean finish, this comfortable essential will be the one layer you can't live without. Our slim fit is designed to fit closer to the body for a modern look.\n", "HIGHLIGHTS", "- 55% Cotton, 25% Acrylic, 15% Nylon, 5% Wool\n- Pull On closure\n- Machine Wash\n- 12-Gauge fabrication is the perfect weight to wear alone or layer over your favorite button down\n- Classic v-neck line design featuring ribbed collar, cuffs, and hem\n- Soft hand cotton feel\n- Available in a broad spectrum of colors.\n", "https://m.media-amazon.com/images/I/717NMQ3RPUL._AC_UX679_.jpg<<<https://m.media-amazon.com/images/I/71zWH5g4WtL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71zWH5g4WtL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/81XouddV3aL._AC_UX569_.jpg", 560000);
        handler.add_item("Goodthreads Men's Lightweight Merino Wool Crewneck Sweater", Item.MALE, "sweaters","PRODUCT DETAILS", "Quality clothes for all the good things ahead. Our brand is stacked with vintage-inspired streetwear for easy looks every day.\n", "HIGHLIGHTS", "- 100% Merino Wool\n- Dry Clean Only\n- Easy through chest and tapered through waist\n- Lightweight and exceptionally soft 100% Merino Wool\n- Crew neckline.\n","https://m.media-amazon.com/images/I/81rEFwcQv5L._AC_UX522_.jpg<<<https://m.media-amazon.com/images/I/81VB4+NkpeL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91fby30k8TL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71AXuIm0j2L._AC_UY550_.jpg", 360000);
        handler.add_item("Essentials Women's Lightweight Mockneck Sweater", Item.FEMALE, "sweaters", "PRODUCT DETAILS", "- 55% Cotton, 25% Modal, 20% Polyester\n- Imported\n- Machine Wash\n- Close-but-comfortable fit with easy movement\n- Lightweight and soft yarn\n- Mock neckline", "", "","https://m.media-amazon.com/images/I/81PydPSGt1L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/8135KYeBIuL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91jOLbM9FtL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71cuyj-hWoL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81bquB0n5uL._AC_UY550_.jpg" ,453000);
        handler.add_item("Essentials Women's Fisherman Cable Turtleneck Sweater",  Item.FEMALE, "sweaters", "PRODUCT DETAILS", "BespokeTailor Essentials is focused on creating affordable, high-quality, and long-lasting everyday clothing you can rely on. Our line of women's apparel includes cashmere sweaters, fleece and down jackets, and more, including plus-size options. Our consistent sizing takes the guesswork out of shopping, and each piece is put to the test to maintain the highest standards in quality and comfort.\n", "HIGHLIGHTS", "- 100% Cotton\n- Machine Wash\n- Close-but-comfortable fit with easy movement\n- Super-soft natural fiber midweight yarn\n- Turtleneck neckline.\n", "https://m.media-amazon.com/images/I/91vdx0N3a6L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91x5XSZfN3L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91-4nttvW8L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91Nl26+X38L._AC_UY550_.jpg", 650000);
        handler.add_item("Hanes Men's Sweatshirt, EcoSmart Fleece Crewneck Sweatshirt, Cotton-Blend Fleece Sweatshirt, Plush Fleece Pullover Sweatshirt", Item.MALE, "sweaters", "PRODUCT DETAILS", "When you're shopping for your next pullover fleece sweatshirt, why not choose one that you can feel good about buying while feeling good wearing? Hanes® EcoSmart® fleece is your new go-to wardrobe staple. Soft and plush, this cozy crewneck sweatshirt is made of mid-weight cotton/poly fleece with up to 5% of the recycled polyester fibers. The fleece in this classic crewneck sweatshirt is low-pill, super-soft, and made to keep its plush comfort for a long time. And it will hold its shape thanks to a ribbed crewneck, cuffs, and hem. Double-needle stitching at the neck and armhole seams further enhance quality and durability. Here's a basic crewneck fleece sweatshirt to wear well and with pride.\n", "HIGHLIGHTS", "- 50% Cotton, 50% Polyester\n- shirts closure.\n- Machine Wash\n- Either tagless or with easily removed tearaway tag for comfort\n- Made with a portion of recycled polyester\n- Patented low-pill fabric\n- Lay flat collar keeps its shape wash after wash\n", "https://m.media-amazon.com/images/I/71eM9NArc6L._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71w3bJLCcBL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71w3bJLCcBL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/61rkeiySh4L._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/61hYTrxGtQL._AC_UX569_.jpg", 700000);

// Polo shirts
        handler.add_item("Lee Uniforms Men's Modern Fit Short Sleeve Polo Shirt", Item.MALE, "polo-shirts", "PRODUCT DETAILS", "WORK, SCHOOL, CASUAL\nThe men’s modern fit short sleeve polo shirt by Lee Uniforms is your go-to top for work, school, casual fashion, and beyond. It’s the perfect complement for practically any business or work dress code, school uniform, and daily wardrobe.\n\nLEE QUALITY\nFeel the quality in every stitch, wash after wash. Each Lee Uniforms polo shirt is built with premium quality, durability, and style, just the way every Lee garment has been since 1889. That’s value you can trust.\n\nMODERN COMFORT\nBusy lifestyles require clothes to match. Lee Uniforms polo shirts are tailored to look great no matter where you wear them, with just the right fit you require, ready to handle light work and everyday use with ease. Stylish, professional, and comfortable.\n\nCONSISTENT FIT\nWe understand how important fit is to you because it’s important to us. Lee Uniforms was born out of a clear desire from the younger, more style conscious consumer who needs clothing sizes to remain consistent. From small to 4XL, you’ll find the right fit with Lee.\n", "HIGHLIGHTS", "- 60% Cotton, 40% Polyester\n- Button closure\n- WORK, SCHOOL, CASUAL: Our classic cotton/polyester blend polo shirt is perfect for any occasion\n- LEE QUALITY: Built with quality, durability, and style that have been Lee staples for over 125 years\n- MODERN COMFORT: Each shirt is carefully crafted to look great and move with you throughout the day\n- Mixed color logo is due to change in Lee packaging\nMULTIPLE COLORS: Choose from 12 colors to mix and match the right hues for work, play, and more\n", "https://m.media-amazon.com/images/I/81y5-Mi9RmL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81grn9+vsZL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91DA5j0M19L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81MQyt3f9kS._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81F9ERxT19L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71SFplFnb1S._AC_UY550_.jpg", 432000);
        handler.add_item("Red Kap Men's Big and Tall Big & Tall Professional Polo Shirt",Item.MALE, "polo-shirts", "PRODUCT DESCRIPTIONS", "Superior color retention, superior wicking, snag and wrinkle resistant grid-texture in a light weight yet durable fabric.", "HIGHLIGHTS", "- 100% Polyester\n- Button closure\n- Machine Wash\n- Inset, double compartment sleeve pocket\n- Set-in sleeve for a professional appearance\n- No-scratch tag less label\n- Textured\n", "https://m.media-amazon.com/images/I/811SzvF1qeL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71OSqFJqIXL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/71Shmtu2PxL._AC_UX466_.jpg",453000);
        handler.add_item("Under Armour Men's Tech Polo",Item.MALE, "polo-shirts","PRODUCT DESCRIPTIONS", "UA Tech™ is our original go-to training gear: Under Armour men's Tech polos are loose, light, and keep you cool. Basically, they're built to be everything you need. Textured fabric that's soft, light & breathable. Material wicks sweat & dries really fast. 3-button placket. Self-fabric collar. Loose: Fuller cut for complete comfort. 100% Polyester.\n", "HIGHLIGHTS", "- Loose: Fuller cut for complete comfort.\n- Textured fabric that's soft, light & breathable\n- Material wicks sweat & dries really fast\n- 3-button placket\n- Self-fabric collar\n", "https://m.media-amazon.com/images/I/51iZBvLXW6L._AC_SX679_.jpg<<<https://m.media-amazon.com/images/I/41sKb5ZECCL._AC_SX679_.jpg<<<https://m.media-amazon.com/images/I/511RNaNTbDL._AC_SX679_.jpg", 560000);
        handler.add_item("Nautica Men's Classic Fit Short Sleeve Dual Tipped Collar Polo Shirt" ,Item.MALE, "polo-shirts","PRODUCT DESCRIPTIONS", "Breathable soft cotton makes this woven polo lightweight enough for warmer weather but still an ideal layering piece under a sweater once the season changes.", "HIGHLIGHTS", "- 100% Cotton\n- Imported\n- Pull On closure\n- Machine Wash\n- Stand collar, 3-button placket closure\n- Ribbed collar & cuffs, hem with slits\n", "https://m.media-amazon.com/images/I/71+nhNAqgXL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/615xDI4bFSL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/81pOUlg0a3L._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/615xDI4bFSL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/71+nhNAqgXL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/81pOUlg0a3L._AC_UX466_.jpg", 650000);
        handler.add_item("Essentials Men's Regular-Fit Cotton Pique Polo Shirt",Item.MALE, "polo-shirts","PRODUCT DESCRIPTIONS", "An Amazon brand - Regular fit through the chest for a relaxed, unrestricted fit with a printed neck label to maximize comfort", "HIGHLIGHTS", "- 100% Cotton\n- Imported\n- Button closure\n- Machine Wash\n- This short-sleeve polo is made with comfortable pique fabric, a double-button placket, and ribbed cuffs for a classic look that never goes out of style\n- Regular fit through the chest for a relaxed, unrestricted fit with a printed neck label to maximize comfort\n- Get these colors before they sell out!\n- Everyday made better: we listen to customer feedback and fine-tune every detail to ensure quality, fit, and comfort\n","https://m.media-amazon.com/images/I/91+8Js6mHdL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91sOGWKklWL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81AY+mfREvL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81AY+mfREvL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81wq4EAzEfL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/91HDxf89jlL._AC_UX522_.jpg", 513000);
        handler.add_item("Essentials Women's Short-Sleeve Polo Shirt (Available in Plus Size)",Item.FEMALE, "polo-shirts","PRODUCT DESCRIPTIONS", "Amazon Essentials is focused on creating affordable, high-quality, and long-lasting everyday clothing you can rely on. Our line of women's apparel includes cashmere sweaters, fleece and down jackets, and more, including plus-size options. Our consistent sizing takes the guesswork out of shopping, and each piece is put to the test to maintain the highest standards in quality and comfort.", "HIGHLIGHTS", "- 94% Cotton, 6% Elastane\n- Imported\n- Machine Wash\n- Close-but-comfortable fit with easy movement\n- Lightweight and breathable pique knit fabric\n- Button-front closure\n", "https://m.media-amazon.com/images/I/910ItTRRfuS._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91CDheOmNQS._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81QeVrAIISS._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71g-ljTts5S._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91mcPzv+CHS._AC_UX466_.jpg", 500000);
        handler.add_item("Hanes Sport Women's Polo Shirt, Women’s Cool DRI Moisture-Wicking Performance Polo Shirt, Women’s Jersey Knit Polo Shirt",Item.FEMALE, "polo-shirts","PRODUCT DESCRIPTIONS", "Want to stay dry no sweat. Our Cool DRI sport shirt's technology keeps you cool and comfortable, even when the competition heats up.", "HIGHLIGHTS", "- 100% Polyester\n- Machine Wash\n- QUALITY FABRIC – Hanes Sport jersey knit fabric works overtime to keep you cool, dry and protected from the sun. (100% Polyester)\n- ODOR PROTECTION – Built with FreshIQ, this odor protecting technology attacks odor-causing bacteria so you can feel fresh all day.\n- QUICK DRY – Hanes Sport women’s polo shirt features innovative Cool DRI technology, allowing the fabric to dry faster. The jersey knit fabric also offers a UPF rating of 50+ for protection against harmful UV rays.\n", "https://m.media-amazon.com/images/I/71MNfUMBaLL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/718Piq5mTLL._AC_UY550_.jpg", 760000);


        // fill rating table
        handler.add_rating(1, "username1", 4.0F);
        handler.add_rating(1, "username5", 3.0F);
        handler.add_rating(2, "username2", 5.0F);
        handler.add_rating(2, "username3", 2.0F);
        handler.add_rating(2, "username4", 5.0F);
        handler.add_rating(3, "username2", 4.0F);
        handler.add_rating(3, "username6", 1.0F);
        handler.add_rating(4, "username5", 3.0F);
        handler.add_rating(3, "username5", 3.0F);

        // fill quantity table
        handler.add_quantity(1, "M", "Black", 21);
        handler.add_quantity(1, "L", "White", 22);
        handler.add_quantity(2, "M", "Red", 23);
        handler.add_quantity(2, "L", "Green", 24);
        handler.add_quantity(3, "M", "Blue", 25);
        handler.add_quantity(3, "L", "Brown", 26);
        handler.add_quantity(4, "M", "Blue", 27);
        handler.add_quantity(5, "M", "White", 28);
        handler.add_quantity(6, "M", "Green", 29);
        handler.add_quantity(6, "L", "Black", 30);
        handler.add_quantity(7, "M", "Black", 31);
        handler.add_quantity(8, "M", "Red", 32);
        handler.add_quantity(8, "L", "Cyan", 33);

        // fill like table
        handler.add_like("username1", 1);
        handler.add_like("username2", 2);
        handler.add_like("username2", 3);
        handler.add_like("username3", 3);
        handler.add_like("username3", 4);
        handler.add_like("username3", 5);
        handler.add_like("username4", 5);
        handler.add_like("username5", 6);
        handler.add_like("username4", 6);

        // fill cart table
        handler.add_cart("username1");
        handler.add_cart_item(1, 1, 3);
        handler.add_cart_item(1, 2, 2);
        handler.add_cart_item(1, 3, 5);
        handler.add_order(1, 100, 10, "cash", 1);

        handler.add_cart("username1");
        handler.add_cart_item(2, 4, 1);
        handler.add_cart_item(2, 5, 2);
        handler.add_cart_item(2, 6, 2);
        handler.add_order(2, 60, 5, "cash", 1);

        handler.add_cart("username2");
        handler.add_cart_item(3, 4, 2);
        handler.add_cart_item(3, 2, 2);
        handler.add_cart_item(3, 1, 4);
        handler.add_order(3, 70, 8, "cash", 1);

        handler.add_cart("username3");
        handler.add_cart_item(4, 1, 5);
        handler.add_cart_item(4, 7, 1);
        handler.add_cart_item(4, 8, 2);
        handler.add_order(4, 80, 10, "cash", 1);*/

        // id 1 -> 5
        handler.add_user("admin123", "Password_123", "admin", "admin", User.MALE, "admin@gmail.com", "0900009000", "01/01/2000", "admin address");
        handler.add_item("Dry Crew Neck Short Sleeve Color T-Shirt", Item.MALE, "T-shirts", "About the Product", "Crafted from soft cotton for an effortless feel, this t-shirt features an oversized monogram logo for an iconic, retro-inspired look. Detailed with a crewneck, a straight hem and twin-needle topstitching in a wide array of colors.",
                "Product details", "- Oversized monogram logo for an iconic, timeless design\n- Soft cotton for effortless, breathable comfort",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/21890825_001_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/21890825_001_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/21890825_001_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                550000);
        handler.add_item("Relaxed Fit Archive Logo Crewneck T-Shirt", Item.MALE, "T-shirts", "About the Product", "Reimagined classics, iconic Calvin. Crafted from soft cotton for an effortless feel, this Calvin Klein t-shirt features an embroidered archive logo at front for an iconic, signature design. Cut in a relaxed fit with a crewneck, a straight hem and twin-needle topstitching.",
                "Product details", "- Embroidered archive logo at front for an iconic, signature design\n- Soft cotton for effortless, breathable comfort",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/21892290_031_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/21892290_031_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/21892290_031_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                500000);
        handler.add_item("Short Sleeve City Graphic T-Shirt", Item.MALE, "T-shirts", "About the Product", "A t-shirt featuring a city graphic print at the front. Made with short sleeves and a crewneck. Finished with a CK monogram logo design at the upper chest.",
                "Product details", "- CK monogram logo design\n- Short sleeves\n- Crewneck\n- City graphic",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/21890870_540_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/21890870_540_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/21890870_540_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                700000);
        handler.add_item("Relaxed Fit Standard Logo Crewneck T-Shirt", Item.FEMALE, "T-shirts", "About the Product", "The quintessential tee, featuring our classic hero logo at front. Cut in a relaxed fit with solid jersey in robust, heavyweight cotton.",
                "Product details", "- Solid jersey in heavyweight cotton\n- Relaxed fit: relaxed through arms, loose fit around body",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/11181430_540_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11181430_540_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11181430_540_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                600000);
        handler.add_item("Performance Logo Tape Cropped T-Shirt", Item.FEMALE, "T-shirts", "About the Product", "Cut in a cropped length, this long-sleeve tee features a fitted silhouette and logo tape styling at the waist for an elevated, performance-ready look. Crafted with stretch for total flexibility and limitless movement.",
                "Product details", "- Long sleeves\n- Cropped length\n- Logo tape styling at the waist",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/11552404_001_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11552404_001_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11552404_001_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                650000);

        // id 6 -> 10
        handler.add_item("Straight Fit Brighton Beach Jeans", Item.MALE, "Jeans", "About the Product", "Designed with a straight fit, these reimagined Calvin Klein denim jeans feature 5-pocket styling and sit at the waist with straight legs. Updated with metal hardware in a light nickel finish, redrawn back pocket omega stitching and a soft back waist logo patch in contrasting colors.",
                "Product details", "- Straight fit: sits at waist and straight leg\n- Extra soft cotton stretch denim for a flexible feel and all-day comfort\n- 5-pockets + belt loops",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/25027090_800_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/25027090_800_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/25027090_800_alternate2?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                680000);
        handler.add_item("Slim Straight Fit Acid Wash Jeans", Item.MALE, "Jeans", "About the Product", "An iconic essential, our reimagined jeans are made with flexible stretch denim for enhanced movement and all-day comfort. Updated with signature metal logo hardware and back pocket omega topstitching, a Calvin Klein hallmark.",
                "Product details", "- Extra soft cotton stretch denim for a flexible feel and all-day comfort\n- Slim straight fit: sits at waist, slim straight leg\n- Care for your denim sustainably - wash sparingly, inside out in cold water, hang dry",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/25567300_460_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/25567300_460_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/25567300_460_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                1000000);
        handler.add_item("Slim Straight Fit Fontaine Medium Stone Jeans", Item.MALE, "Jeans", "About the Product", "An iconic essential, our reimagined jeans are made with flexible stretch denim for enhanced movement and all-day comfort. Updated with signature metal logo hardware and back pocket omega topstitching, a Calvin Klein hallmark.",
                "Product details", "- Extra soft cotton stretch denim for a flexible feel and all-day comfort\n- Slim straight fit: sits at waist, slim straight leg",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/25507211_400_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/25507211_400_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/25507211_400_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                950000);
        handler.add_item("Women's High Rise Skinny Fit Comfort Stretch Jeans", Item.FEMALE, "Jeans", "About the Product", "Designed with a high rise skinny fit, these reimagined denim jeans feature 5-pocket styling and are slim through the hip and thigh with skinny legs. Updated with a comfort stretch denim for all day comfort, redrawn back pocket omega stitching and a CKJ logo patch at the back waist.",
                "Product details", "- Crafted with comfort stretch denim\n- High rise, slim through hip and thigh + skinny leg\n- Back pocket logo tag + signature omega topstitching",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/15744567_010_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/15744567_010_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/15744567_010_alternate2?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                950000);
        handler.add_item("Slim Fit Super High Rise Light Blue Ankle Jeans", Item.FEMALE, "Jeans", "About the Product", "Classic jeans in a light blue wash, updated with a super high rise waist and slim legs. Features destructed detailing, metal logo hardware, a back waist logo patch and back pocket signature omega topstitching.",
                "Product details", "- Cotton stretch denim blend\n- Super high rise waist\n- Slim leg + ankle length",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/15564599_010_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/15564599_010_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/15564599_010_alternate2?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                900000);

        // id 11 -> 15
        handler.add_item("Relaxed Fit Archive Logo Fleece Hoodie", Item.MALE, "Hoodies", "About the Product", "Reimagined classics, iconic Calvin. Designed with an archive-inspired logo, this Calvin Klein sweatshirt features a plush cotton knit fleece blend for premium, all-day comfort. Cut in a relaxed fit with a drawstring hood and ribbed knit trim.",
                "Product details", "- Embroidered archive logo for a retro-inspired, signature look\n- Plush cotton fleece blend for premium, all-day comfort\n- Relaxed fit: relaxed through arms, loose fit around body",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/21652560_401_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/21652560_401_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/21652560_401_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                920000);
        handler.add_item("Ombre Pullover Sweater Hoodie", Item.MALE, "Hoodies", "About the Product", "Styled with an ombre design, this hoodie features a two-toned, dimensional look. Made with a kangaroo pocket at the front and ribbed knit detailing at the cuffs and hem. Finished with an embroidered CK monogram logo at the chest.",
                "Product details", "- Ombre design\n- Long sleeves + crossover hood\n- Ribbed knit cuffs and hem",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/23403240_030_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/23403240_030_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/23403240_030_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                1500000);
        handler.add_item("Archive Logo Fleece Hoodie", Item.FEMALE, "Hoodies", "About the Product", "A timeless design, straight from the archive. Designed with a retro-inspired embroidered archive logo, this hoodie sweatshirt features a plush cotton knit fleece blend for premium, all-day comfort. Cut in a relaxed fit with a fine ribbed knit trim.",
                "Product details", "- Compact embroidered archive logo for a retro-inspired, signature look\n- Plush cotton fleece blend for premium, all-day comfort\n- Relaxed fit: relaxed through arms, loose fit around body",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/11161000_001_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11161000_001_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11161000_001_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                950000);
        handler.add_item("Recycled Polar Fleece Hoodie", Item.FEMALE, "Hoodies","About the Product", "Cut in a relaxed fit, this hoodie is made from plush fleece for an extra soft feel and endless comfort. Designed in a cropped length with a drawstring hood and rib-knit cuffs. Finished with Calvin Klein embroidery on the chest.",
                "Product details", "- Soft-touch polar fleece in a sustainable fabric blend\n- Relaxed fit, cropped\n- Branded drawstring ends",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/11869762_159_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11869762_159_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11869762_159_alternate2?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                1700000);
        handler.add_item("Performance Logo Tape Hoodie", Item.FEMALE, "Hoodies", "About the Product", "Crafted from a plush cotton and recycled fleece blend, this performance-ready hoodie is made with an extra soft hand for all-day comfort. Designed with a drawstring hood and a front pocket. Finished with signature logo tape styling along the sleeves.",
                "Product details", "- Drawstring hood\n- Logo tape styling along the sleeves\n- Banded cuffs",
                "https://calvinklein.scene7.com/is/image/CalvinKlein/11552316_030_main?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11552316_030_alternate1?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0<<<https://calvinklein.scene7.com/is/image/CalvinKlein/11552316_030_alternate3?wid=1500&hei=1976&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
                800000);

// Shorts
        // id 16 -> 24
        handler.add_item("Men's 7\" breathable sports short", Item.MALE, "Shorts", "Breathable 7\" Recycle Men's Sports Shorts", "BespokeTailor has introduced a variety of sports products made from various materials, including Maxcool, Poly Quickdry, and... Following on from previous sports products and the garment industry trend of \"sustainable fashion\", BespokeTailor launched Product eyes 7\" Recycle men's sports pants that are environmentally friendly, with the main ingredient being 100% Recycled yarn.","HIGHLIGHTS", "- Fabric: 100% recycled yarn that adheres to sustainable fashion trends.\n- Advantages: Longevity, less wrinkles, and good form retention.\n- Quickdry (quick drying) + Wicking (fast absorbing) + Stretch are the application technologies (Stretch).\n-Sporty design with the ideal length for all sports activities\n- The belt has an elastic band that allows guys to adjust the elasticity, making it suitable for the waistline.\n- 7 inch pants length suitable for sports activities such as running, sports, etc.\n- Wicking technology (Quick Absorption) provides many outstanding features: cooling and breathability ", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_1.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_3.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_2.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_7.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_4.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/7_recycle_xam_nhat_5.jpg",239000);
        handler.add_item("New French Terry V2 Men's Shorts (embroidered logo)", Item.MALE, "Shorts","Product details","New French Terry Shorts men's pants combine with CVC weave - a weave that creates more air between the fibers to give you a more airy and cooler wearing experience, we want your activities to be comfortable. more convenient, easier and faster, even if it's just everyday activities, so simple that no one wants to care.", "HIGHLIGHTS", "- Lighter: help men always feel comfortable and confident when wearing pants on their body\n- Breathable: does not leave an unpleasant smell after a long day of exercise\n- Absorbency: maximum perspiration absorption\n- Stretch: 4-way stretch is always comfortable when moving.\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/terry_shorts_xam_1.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/terry_shorts_xam_2.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/terry_shorts_xam_3.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/terry_shorts_xam_4.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/September2022/134-4.jpg", 250000);
        handler.add_item("5\" New Ultra Men's Sports Shorts (with split hem & back zip pocket)", Item.MALE, "Shorts", "Design Men's Sports Shorts 5\" New Ultra", "We has designed the best for men's shorts, providing the most comfortable and convenient men's shorts:\n- Elastic waistband and internal drawstring for convenient fit adjustment.\n- The back pocket has a convenient YKK zipper, along with 2 side pockets for convenient personal belongings.\n- Split hem is convenient for all activities with logo design for sportiness.\n", "HIGHLIGHTS", "- Suitable for: sports activities\n- Application technology: Quick Dry (quick drying) + Wicking (fast absorbing) + Stretch (Stretch)\n- Vải được cung từ Promax, công ty vải hàng đầu thế giới trong lĩnh vực thể thao.\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01225-copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01238-copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01253-copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01259-copy_65.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC01503-copy-den.jpg",  189000);
        handler.add_item("7\" Stretch Nylon Outdoor Shorts (with back pocket)", Item.MALE, "Shorts", "Product details", "With a basic design that is suitable for all shapes of men who are currently aiming for and very fond of:\n- Elastic waistband with drawstring outside, easy to adjust to fit around the waist\n- YKK zipper pockets along the sides of the pants, Lifetime warranty by Coolmate\n- There is an extra pocket on the back, easy and convenient to fit your wallet, iphone promax and above\n", "HIGHLIGHTS", "- Suitable for: picnics, experiences or intense activities\n- Pants length: 7 inches\n- Durable\n- Much cooler than polyester fabric\n- Good stretch\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23_2.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23_3.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23_1.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/outdor23_4.jpg", 289000);
        handler.add_item("Movement 7\" stretch men's sports shorts", Item.MALE, "Shorts", "Product details", "- Ultra-light fabric is only 106 gsm, giving the feeling of wearing nothing\n- Fabric finishing technology makes the pants comfortable, dry and comfortable for light running and gym activities\n- Double Weaving weave gives a Cooling feeling to wear.\n- Mix in Sporty/Athleisure style with a tank top with sports shoes and running shoes\n- Mix in a casual style with T-shirts, polo shirts.\n", "HIGHLIGHTS", "- With an ultra-lightweight fabric of only 106 gsm, it feels like you're not wearing it\n- The fabric is dyed with Zero Water Discharge technology to pursue the trend of sustainable fashion elements\n- Quick-wicking, 4-way stretch and quick-drying fabric.\n- Suit for: wear light running sports or gym.\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/DSC01693-copyxam7_36.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/DSC00679_copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/DSC00690_copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/DSC00695_copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/July2022/DSC00721_copy.jpg", 239000);
        handler.add_item("Breathable ProMax-S1 Men's Sports Shorts", Item.MALE, "Shorts", "Product details", "Feel the softness and smoothness at the first touch. And just wearing experience, you will definitely like and always choose this high-quality shorts every day.\n    Coolmate is sure that you will want to choose pants to not only feel comfortable but also individual items to make you more beautiful, making people look at you and say \"You look so good in these pants!\"\n This is also the material used by Coolmate in the line of sports polo shirts and has received a lot of positive feedback and love from customers. Surely Promax-S1 Men's Sports Shorts will also give you the most comfort and effective movement.\n", "HIGHLIGHTS", "- Advantages: Cool, breathable, deodorant.\n- Application technology: Quickdry (quick drying) and Wicking (absorbent)\n- Suit for: wear at home.\n", "https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/August2022/_MG_0190_(1).jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/DSC05891-copy.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/May2022/thumb_quan_promax_den.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/April2022/quanpromax_7.jpg<<<https://media.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/April2022/quanpromax_8.jpg", 189000);
        handler.add_item("Taydey Metallic Shorts for Women Hot Sparkly Shiny Shorts with Elastic Drawstring", Item.FEMALE, "Shorts","Product Details","- Fashion and Sports Outfit: Metallic Sparkly Shorts are perfect for fantastic 80's themed parties,yoga,disco,workout,exercise,fitness,dance,clubs,night out,cosplay,hallowen costumes,carnival,christmas,new year party, make you attractive during the activity.\n Functional Design: These shiny metallic shorts, featured with practical side pockets, will offer you comfortable wearing experience as well as stylish look. Get ready for festivals in these stunning rave shorts.\n- Sexy bright colors: Silver Shorts,Gold Shorts,Green Shorts,Blue Shorts,Purple Shorts,Black Shorts,Pink Shorts,Red Shorts,Multicolor Silver Shorts,Teal Shorts,any of them is perfect for your party day\n", "HIGHLIGHTS", "- Imported\n- Drawstring closure\n- Material for hot shiny shorts: 100% Polyester.Shiny ,Skin-friendly, breathable, lightweight, soft and comfortable touch.\n- Main Feature for metallic shorts: Inspired by the traditional dolphin hem shorts,our metallic short for woman is equipped with an elastic waist and adjustable drawstring in the front, offering a loose and flattering fit.\n- 100% Polyester", "https://m.media-amazon.com/images/I/81YPKVhLcvL._AC_UX522_.jpg<<<https://m.media-amazon.com/images/I/81ft+pyEPLL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/81UeGcXxHgL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71LmL0j2b7L._AC_UY550_.jpg",300000);
        handler.add_item("Mounblun Women's Yoga Lounge Shorts Hiking Active Running Workout Shorts Comfy Travel Casual Shorts with Pockets", Item.FEMALE, "Shorts", "Product Details", "- Sweat shorts are perfect for yoga, running, travel, hiking, workout, walking or daily wear. They're light, cool, breathable and stretchy, making it a great summer short for vacation\n- Two sides hand pockets to hold small essentials like a key, card or cash etc; Comfy, wide waistband stays put to ensure all-day comfort; Adjustable drawcord for a custom fit.\n", "HIGHLIGHTS", "- Excellent Flatlock stitching reduces chafing, provide next-to-skin softness and chafe-free comfort.\n- Drawstring closure\n- Imported.\n", "https://m.media-amazon.com/images/I/61tPojEhMlL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/61+SuQtUlbL._AC_UX522_.jpg<<<https://m.media-amazon.com/images/I/51OIzyNC6cL._AC_UY550_.jpg",350000);
        handler.add_item("Women's Mid-Rise 7\" (approx. 18cm) Biker Shorts", Item.FEMALE,"Shorts", "Product Details", "Train like a pro and crush your goals. The soft, stretchy fabric of these biker shorts hugs your body for gentle support, while sweat-wicking technology helps you stay dry when you're pushing through your final set.\n\nSweat-Wicking Power\nNike Dri-FIT Technology moves sweat away from your skin for quicker evaporation, helping you stay dry and comfortable.\n\nFuturistic Style\nBright neon linear graphics map the body and frame the hips for a strong, futuristic look.", "HIGHLIGHTS", "- 78–83% polyester/18–22% elastane.\n- Material percentage may vary. Check label for actual content.\n- 18cm (approx.) inseam\n- Mid-rise waistband\n", "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/efb14c3c-ca1a-4adc-b6e2-9d76ca5d9d32/pro-mid-rise-7-biker-shorts-5cqF51.png<<<https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/648292a7-ef9b-43cd-8f7e-e35e23216f51/pro-mid-rise-7-biker-shorts-5cqF51.png<<<https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/efb14c3c-ca1a-4adc-b6e2-9d76ca5d9d32/pro-mid-rise-7-biker-shorts-5cqF51.png", 500000);


// Sweater
        // id 25 -> 31
        handler.add_item("Essentials Men's Crewneck Sweater", Item.MALE, "Sweaters", "PRODUCT DETAILS", "- Black solid pullover sweater, has a V-neck, long sleeves, and ribbed hem\n- Material: Acrylic\n- Machine Wash\n", "HIGHLIGHTS", "- 100% Cotton\n- Machine Wash\n- This casual wardrobe-essential comes in a lightweight fabric perfect for comfortable everyday wear\n- Features ribbing on the collar, hem, and cuffs to keep you warm\n- Everyday made better: we listen to customer feedback and fine-tune every detail to ensure quality, fit, and comfort\n", "https://m.media-amazon.com/images/I/91nG7tYFJ4L._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/91Z-b-OtcgL._AC_SY550._SX._UX._SY._UY_.jpg<<<https://m.media-amazon.com/images/I/81+SpBJGOuL._AC_UX522_.jpg<<<https://m.media-amazon.com/images/I/81PDMaQeDVL._AC_SY550._SX._UX._SY._UY_.jpg", 500000);
        handler.add_item("Essentials Men's Full-Zip Cotton Sweater", Item.MALE, "Sweaters", "PRODUCT DETAILS", " Our line of men’s must-haves includes polo shirts, chino pants, classic-fit shorts, casual button-downs, and crew-neck tees. Our consistent sizing takes the guesswork out of shopping, and each piece is put to the test to maintain the highest standards in quality and comfort", "HIGHLIGHTS", "- 100% Cotton\n- Machine Wash\n- This cotton sweater is perfect on its own or as a layer under a blazer or jacket\n- Full-zip front, with side pockets and ribbing at the cuffs and hem\n- Everyday made better: we listen to customer feedback and fine-tune every detail to ensure quality, fit, and comfort\n","https://m.media-amazon.com/images/I/71mW2Bu61HL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/811968h0yxL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71IHaAVOISL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81dbTeXisPL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/61FJbEsliDL._AC_UY550_.jpg", 600000);
        handler.add_item("IZOD Men's Premium Essentials Solid V-Neck 12 Gauge Sweater", Item.MALE,"Sweaters", "PRODUCT DETAILS", "This classic men's V-neck sweater adds a dose of ivy league style to any look. With a logo-free design for a clean finish, this comfortable essential will be the one layer you can't live without. Our slim fit is designed to fit closer to the body for a modern look.\n", "HIGHLIGHTS", "- 55% Cotton, 25% Acrylic, 15% Nylon, 5% Wool\n- Pull On closure\n- Machine Wash\n- 12-Gauge fabrication is the perfect weight to wear alone or layer over your favorite button down\n- Classic v-neck line design featuring ribbed collar, cuffs, and hem\n- Soft hand cotton feel\n- Available in a broad spectrum of colors.\n", "https://m.media-amazon.com/images/I/717NMQ3RPUL._AC_UX679_.jpg<<<https://m.media-amazon.com/images/I/71zWH5g4WtL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71zWH5g4WtL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/81XouddV3aL._AC_UX569_.jpg", 560000);
        handler.add_item("Goodthreads Men's Lightweight Merino Wool Crewneck Sweater", Item.MALE, "Sweaters","PRODUCT DETAILS", "Quality clothes for all the good things ahead. Our brand is stacked with vintage-inspired streetwear for easy looks every day.\n", "HIGHLIGHTS", "- 100% Merino Wool\n- Dry Clean Only\n- Easy through chest and tapered through waist\n- Lightweight and exceptionally soft 100% Merino Wool\n- Crew neckline.\n","https://m.media-amazon.com/images/I/81rEFwcQv5L._AC_UX522_.jpg<<<https://m.media-amazon.com/images/I/81VB4+NkpeL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91fby30k8TL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71AXuIm0j2L._AC_UY550_.jpg", 360000);
        handler.add_item("Essentials Women's Lightweight Mockneck Sweater", Item.FEMALE, "Sweaters", "PRODUCT DETAILS", "- 55% Cotton, 25% Modal, 20% Polyester\n- Imported\n- Machine Wash\n- Close-but-comfortable fit with easy movement\n- Lightweight and soft yarn\n- Mock neckline", "", "","https://m.media-amazon.com/images/I/81PydPSGt1L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/8135KYeBIuL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91jOLbM9FtL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71cuyj-hWoL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81bquB0n5uL._AC_UY550_.jpg" ,453000);
        handler.add_item("Essentials Women's Fisherman Cable Turtleneck Sweater",  Item.FEMALE, "Sweaters", "PRODUCT DETAILS", "BespokeTailor Essentials is focused on creating affordable, high-quality, and long-lasting everyday clothing you can rely on. Our line of women's apparel includes cashmere sweaters, fleece and down jackets, and more, including plus-size options. Our consistent sizing takes the guesswork out of shopping, and each piece is put to the test to maintain the highest standards in quality and comfort.\n", "HIGHLIGHTS", "- 100% Cotton\n- Machine Wash\n- Close-but-comfortable fit with easy movement\n- Super-soft natural fiber midweight yarn\n- Turtleneck neckline.\n", "https://m.media-amazon.com/images/I/91vdx0N3a6L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91x5XSZfN3L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91-4nttvW8L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91Nl26+X38L._AC_UY550_.jpg", 650000);
        handler.add_item("Hanes Men's Sweatshirt, EcoSmart Fleece Crewneck Sweatshirt, Cotton-Blend Fleece Sweatshirt, Plush Fleece Pullover Sweatshirt", Item.MALE, "Sweaters", "PRODUCT DETAILS", "When you're shopping for your next pullover fleece sweatshirt, why not choose one that you can feel good about buying while feeling good wearing? Hanes® EcoSmart® fleece is your new go-to wardrobe staple. Soft and plush, this cozy crewneck sweatshirt is made of mid-weight cotton/poly fleece with up to 5% of the recycled polyester fibers. The fleece in this classic crewneck sweatshirt is low-pill, super-soft, and made to keep its plush comfort for a long time. And it will hold its shape thanks to a ribbed crewneck, cuffs, and hem. Double-needle stitching at the neck and armhole seams further enhance quality and durability. Here's a basic crewneck fleece sweatshirt to wear well and with pride.\n", "HIGHLIGHTS", "- 50% Cotton, 50% Polyester\n- shirts closure.\n- Machine Wash\n- Either tagless or with easily removed tearaway tag for comfort\n- Made with a portion of recycled polyester\n- Patented low-pill fabric\n- Lay flat collar keeps its shape wash after wash\n", "https://m.media-amazon.com/images/I/71eM9NArc6L._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71w3bJLCcBL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71w3bJLCcBL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/61rkeiySh4L._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/61hYTrxGtQL._AC_UX569_.jpg", 700000);


// Polo shirts
        // id 32 -> 38
        handler.add_item("Lee Uniforms Men's Modern Fit Short Sleeve Polo Shirt", Item.MALE, "Polo-shirts", "PRODUCT DETAILS", "WORK, SCHOOL, CASUAL\nThe men’s modern fit short sleeve polo shirt by Lee Uniforms is your go-to top for work, school, casual fashion, and beyond. It’s the perfect complement for practically any business or work dress code, school uniform, and daily wardrobe.\n\nLEE QUALITY\nFeel the quality in every stitch, wash after wash. Each Lee Uniforms polo shirt is built with premium quality, durability, and style, just the way every Lee garment has been since 1889. That’s value you can trust.\n\nMODERN COMFORT\nBusy lifestyles require clothes to match. Lee Uniforms polo shirts are tailored to look great no matter where you wear them, with just the right fit you require, ready to handle light work and everyday use with ease. Stylish, professional, and comfortable.\n\nCONSISTENT FIT\nWe understand how important fit is to you because it’s important to us. Lee Uniforms was born out of a clear desire from the younger, more style conscious consumer who needs clothing sizes to remain consistent. From small to 4XL, you’ll find the right fit with Lee.\n", "HIGHLIGHTS", "- 60% Cotton, 40% Polyester\n- Button closure\n- WORK, SCHOOL, CASUAL: Our classic cotton/polyester blend polo shirt is perfect for any occasion\n- LEE QUALITY: Built with quality, durability, and style that have been Lee staples for over 125 years\n- MODERN COMFORT: Each shirt is carefully crafted to look great and move with you throughout the day\n- Mixed color logo is due to change in Lee packaging\nMULTIPLE COLORS: Choose from 12 colors to mix and match the right hues for work, play, and more\n", "https://m.media-amazon.com/images/I/81y5-Mi9RmL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81grn9+vsZL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91DA5j0M19L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81MQyt3f9kS._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81F9ERxT19L._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71SFplFnb1S._AC_UY550_.jpg", 432000);
        handler.add_item("Red Kap Men's Big and Tall Big & Tall Professional Polo Shirt",Item.MALE, "Polo-shirts", "PRODUCT DESCRIPTIONS", "Superior color retention, superior wicking, snag and wrinkle resistant grid-texture in a light weight yet durable fabric.", "HIGHLIGHTS", "- 100% Polyester\n- Button closure\n- Machine Wash\n- Inset, double compartment sleeve pocket\n- Set-in sleeve for a professional appearance\n- No-scratch tag less label\n- Textured\n", "https://m.media-amazon.com/images/I/811SzvF1qeL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/71OSqFJqIXL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/71Shmtu2PxL._AC_UX466_.jpg",453000);
        handler.add_item("Under Armour Men's Tech Polo",Item.MALE, "Polo-shirts","PRODUCT DESCRIPTIONS", "UA Tech™ is our original go-to training gear: Under Armour men's Tech polos are loose, light, and keep you cool. Basically, they're built to be everything you need. Textured fabric that's soft, light & breathable. Material wicks sweat & dries really fast. 3-button placket. Self-fabric collar. Loose: Fuller cut for complete comfort. 100% Polyester.\n", "HIGHLIGHTS", "- Loose: Fuller cut for complete comfort.\n- Textured fabric that's soft, light & breathable\n- Material wicks sweat & dries really fast\n- 3-button placket\n- Self-fabric collar\n", "https://m.media-amazon.com/images/I/51iZBvLXW6L._AC_SX679_.jpg<<<https://m.media-amazon.com/images/I/41sKb5ZECCL._AC_SX679_.jpg<<<https://m.media-amazon.com/images/I/511RNaNTbDL._AC_SX679_.jpg", 560000);
        handler.add_item("Nautica Men's Classic Fit Short Sleeve Dual Tipped Collar Polo Shirt" ,Item.MALE, "Polo-shirts","PRODUCT DESCRIPTIONS", "Breathable soft cotton makes this woven polo lightweight enough for warmer weather but still an ideal layering piece under a sweater once the season changes.", "HIGHLIGHTS", "- 100% Cotton\n- Imported\n- Pull On closure\n- Machine Wash\n- Stand collar, 3-button placket closure\n- Ribbed collar & cuffs, hem with slits\n", "https://m.media-amazon.com/images/I/71+nhNAqgXL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/615xDI4bFSL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/81pOUlg0a3L._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/615xDI4bFSL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/71+nhNAqgXL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/81pOUlg0a3L._AC_UX466_.jpg", 650000);
        handler.add_item("Essentials Men's Regular-Fit Cotton Pique Polo Shirt",Item.MALE, "Polo-shirts","PRODUCT DESCRIPTIONS", "An Amazon brand - Regular fit through the chest for a relaxed, unrestricted fit with a printed neck label to maximize comfort", "HIGHLIGHTS", "- 100% Cotton\n- Imported\n- Button closure\n- Machine Wash\n- This short-sleeve polo is made with comfortable pique fabric, a double-button placket, and ribbed cuffs for a classic look that never goes out of style\n- Regular fit through the chest for a relaxed, unrestricted fit with a printed neck label to maximize comfort\n- Get these colors before they sell out!\n- Everyday made better: we listen to customer feedback and fine-tune every detail to ensure quality, fit, and comfort\n","https://m.media-amazon.com/images/I/91+8Js6mHdL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91sOGWKklWL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81AY+mfREvL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81AY+mfREvL._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81wq4EAzEfL._AC_UX466_.jpg<<<https://m.media-amazon.com/images/I/91HDxf89jlL._AC_UX522_.jpg", 513000);
        handler.add_item("Essentials Women's Short-Sleeve Polo Shirt (Available in Plus Size)",Item.FEMALE, "Polo-shirts","PRODUCT DESCRIPTIONS", "Amazon Essentials is focused on creating affordable, high-quality, and long-lasting everyday clothing you can rely on. Our line of women's apparel includes cashmere sweaters, fleece and down jackets, and more, including plus-size options. Our consistent sizing takes the guesswork out of shopping, and each piece is put to the test to maintain the highest standards in quality and comfort.", "HIGHLIGHTS", "- 94% Cotton, 6% Elastane\n- Imported\n- Machine Wash\n- Close-but-comfortable fit with easy movement\n- Lightweight and breathable pique knit fabric\n- Button-front closure\n", "https://m.media-amazon.com/images/I/910ItTRRfuS._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91CDheOmNQS._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/81QeVrAIISS._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/71g-ljTts5S._AC_UY550_.jpg<<<https://m.media-amazon.com/images/I/91mcPzv+CHS._AC_UX466_.jpg", 500000);
        handler.add_item("Hanes Sport Women's Polo Shirt, Women’s Cool DRI Moisture-Wicking Performance Polo Shirt, Women’s Jersey Knit Polo Shirt",Item.FEMALE, "Polo-shirts","PRODUCT DESCRIPTIONS", "Want to stay dry no sweat. Our Cool DRI sport shirt's technology keeps you cool and comfortable, even when the competition heats up.", "HIGHLIGHTS", "- 100% Polyester\n- Machine Wash\n- QUALITY FABRIC – Hanes Sport jersey knit fabric works overtime to keep you cool, dry and protected from the sun. (100% Polyester)\n- ODOR PROTECTION – Built with FreshIQ, this odor protecting technology attacks odor-causing bacteria so you can feel fresh all day.\n- QUICK DRY – Hanes Sport women’s polo shirt features innovative Cool DRI technology, allowing the fabric to dry faster. The jersey knit fabric also offers a UPF rating of 50+ for protection against harmful UV rays.\n", "https://m.media-amazon.com/images/I/71MNfUMBaLL._AC_UX569_.jpg<<<https://m.media-amazon.com/images/I/718Piq5mTLL._AC_UY550_.jpg", 760000);




// Skirts
        // id 39 -> 42
        handler.add_item("WIND.RDY stretch flared skirt", Item.FEMALE, "Skirts", "PRODUCT DESCRIPTION", "A GOLF SKIRT FOR WINDY ROUNDS MADE IN PART WITH RECYCLED CONTENT.\nPlay with confidence on windy days. This adidas golf skirt is made with WIND.RDY to keep you going in breezy conditions. Attached undershorts let you swing and bend freely. The flared design keeps your style on point.\nMade in part with recycled content generated from production waste, e.g. cutting scraps, and post-consumer household waste to avoid the larger environmental impact of producing virgin content.", "DETAILS", "- Regular fit\n- Waist-support construction with belt loops\n- 88% recycled polyester, 12% elastane doubleweave\n- Attached undershorts\n- Do not bleach or dry clean\n- Machine wash cold\n", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/f83d511d36b04595b6c8ae7101272c8f_9366/WIND.RDY_Stretch_Flared_Skirt_Pink_HG1717_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6d21b80427f342dab31dae710125b74f_9366/WIND.RDY_Stretch_Flared_Skirt_White_HG1716_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/231a2464a4ed441cba31ae71002a401e_9366/WIND.RDY_Stretch_Flared_Skirt_Blue_HG1720_25_model.jpg", 750000);
        handler.add_item("3-stripes sweater skirt", Item.FEMALE, "Skirts", "PRODUCT DESCRIPTION", "A GOLF SKIRT WITH A SOFT FEEL, MADE IN PART WITH RECYCLED MATERIALS.\nCan a golf skirt be both sleek and sporty? We think so. This one from adidas has the feel of a lightweight knit sweater, with flexibility that lets you move freely. The ribbed waist ensures a stay-put fit, and attached inner tights let you swing and bend with confidence. Iconic 3-Stripes down each side complete the look.\nMade with a series of recycled materials, and at least 60% recycled content, this product represents just one of our solutions to help end plastic waste.\n", "DETAILS", "- Regular fit\n- Ribbed waist\n- 54% recycled polyester, 20% polyacrylics, 20% recycled nylon, 6% wool knit\n- Attached inner tights\n", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2d6c7473ff9e41dbaa34ae7f017cc250_9366/3-Stripes_Sweater_Skirt_Green_HG1271_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/799c9a99d0534fe589c3ae7f017baf26_9366/3-Stripes_Sweater_Skirt_Green_HG1271_23_hover_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d3d510f7cc844988aa6dae83015df5fe_9366/3-Stripes_Sweater_Skirt_Green_HG1271_01_laydown.jpg", 700000);
        handler.add_item("Graphic skirt", Item.FEMALE, "Skirts",  "PRODUCT DESCRIPTION", "A GOLF SKIRT WITH BOLD STYLE, MADE IN PART WITH RECYCLED MATERIALS.\nTee off in bold style in this adidas golf skirt. The stretchy fabric is made with moisture-absorbing AEROREADY to keep you dry and comfortable. Inner shorts allow for freedom of movement on the course. The allover graphic gives a shoutout to the Three Stripe Life.\nMade with a series of recycled materials, and at least 60% recycled content, this product represents just one of our solutions to help end plastic waste.", "DETAILS", "- Regular fit\n- Belt loops\n- Skirt: 88% recycled nylon, 12% elastane twill\n-  Inner shorts: 82% recycled polyester, 18% elastane mesh\n- Moisture-absorbing AEROREADY\n- Allover adidas graphics\n", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8383d596a5d241bb8fdeadc8017403e9_9366/Graphic_Skirt_Blue_HA3278_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c7c34d356ab74db794bfadc801774326_9366/Graphic_Skirt_Black_HA3277_25_model.jpg",  620000);
        handler.add_item("Utility skirt", Item.FEMALE, "Skirts",  "PRODUCT DESCRIPTION", "A 3-STRIPES SKIRT MIXING ELEGANCE WITH UTILITY.\n Why limit yourself? Defy genres and dodge expectation in this adidas skirt that mixes sweet, sport and a little something extra – utility. Pockets hold your essentials as you breeze down city sidewalks. Ruched panels at the bottom steal the show with every step or spin. The final touch? 3-Stripes down the sides.", "DETAILS", "- Loose fit\n- Drawcord on elastic waist\n- 100% nylon ripstop\n- Front and back pockets\n", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e00379560ef046039ab3ad1900d26a89_9366/Utility_Skirt_Black_H15782_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bc1b8cac92f468cb2f1ad48011528d0_9366/Utility_Skirt_Black_H15782_01_laydown.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/38d76033586f4f92bb30ad1900d261d8_9366/Utility_Skirt_Black_H15782_23_hover_model.jpg", 400000);

// Jackets
        // id 43 -> 47
        handler.add_item("Spain anthem jacket", Item.MALE, "Jackets" ,  "PRODUCT DESCRIPTION", "A REVERSIBLE JACKET FOR THE PROUDEST MOMENTS, MADE WITH RECYCLED MATERIALS.\nWhen you take on the world, unity is a must. Whichever kit they're wearing beneath it, this adidas football jacket helps the Spain starting XI look like a team. Its reversible design means it complements their classic home colours as well as their art deco-inspired away kit. However you wear it, a team badge shows you stand with your team. Made with 100% recycled materials, this product represents just one of our solutions to help end plastic waste.", "DETAILS", "- Regular fit\n- Full zip with stand-up collar\n- Outer shell: 100% recycled nylon plain weave\n- Inner Shell: 100% recycled polyester twill\n- Elastic cuffs and hem\n- Reversible\n- Plain weave,Twill - right hand", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/daddfab60460436dba13ae8b0103d079_9366/Spain_Anthem_Jacket_Red_HE8920_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e082ae754dbe42d397bdae8b0103bd66_9366/Spain_Anthem_Jacket_Red_HE8920_27_model_hover.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/1a2bf5d78460456badb5aeb300f51ad4_9366/Spain_Anthem_Jacket_Red_HE8920_01_laydown.jpg", 475000);
        handler.add_item("PRSVE outer jacket", Item.MALE, "Jackets" ,  "PRODUCT DESCRIPTION", "A PRACTICAL JACKET MADE WITH RECYCLED MATERIALS.\n A warm jacket that won't weigh you down. This adidas jacket works great for weekends spent hiking, biking and getting out in nature. It has a loose fit to allow for plenty of layers. And the drawcord hood and bungee-adjustable hem work together to lock in warmth. If you're wearing a backpack with a hip belt, you can still keep your essentials close thanks to the roomy chest pockets.\nMade with 100% recycled materials, this product represents just one of our solutions to help end plastic waste.", "DETAILS", "- Loose fit\n- Full zip with drawcord-adjustable hood\n- 100% recycled polyester plain weave\n- Bungee-adjustable hem", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/5de02496f6bb4bf3acbdae4a00a23e1b_9366/PRSVE_Outer_Jacket_Beige_HM2708_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9f8e9ee6392946daa6afae30000eb056_9366/PRSVE_Outer_Jacket_Beige_HM2708_01_laydown.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b455ce9e9c9f4ef6bf4dae4a00a06d35_9366/PRSVE_Outer_Jacket_Black_HM2707_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ab469b625dd548128d46ae30000f34d3_9366/PRSVE_Outer_Jacket_Black_HM2707_01_laydown.jpg", 800000);
        handler.add_item("Statement full-zip jacket", Item.MALE, "Jackets" ,  "PRODUCT DESCRIPTION", "A GOLF JACKET WITH AN ELEVATED FEEL, MADE IN PART WITH RECYCLED MATERIALS.\nLooking and feeling your best makes a difference on the course. Find your competitive edge in this adidas golf jacket. Its double weave fabric offers warmth and weather resistance to keep you comfortable through a range of conditions, plus it has stretch in all the right places for a natural, unrestricted swing. Inside, the brushed fleece is soft against the skin. The textured exterior lends it an elevated feel.", "DETAILS", "- Regular fit\n- Full zip with stand-up collar\n- Main: 92% recycled polyester, 8% elastane double weave\n- Front body, collar and sleeves: 100% recycled polyester polar fleece\n- Durable water-repellent (DWR) coating", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3475298b35454a3297bdae750018fe00_9366/Statement_Full-Zip_Jacket_Black_HM7375_22_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/50b6ae04c2e94335b5fdae75001a660c_9366/Statement_Full-Zip_Jacket_Black_HM7375_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/511cf945e7f74f69819aae600138e33d_9366/Statement_Full-Zip_Jacket_Black_HM7375_01_laydown.jpg", 625000);
        handler.add_item("Frostguard Recycled Content Full-Zip Padded Jacket", Item.MALE, "Jackets" ,  "PRODUCT DESCRIPTION", "A GOLF JACKET WITH QUILTED DOWN INSULATION.\n When golf is your game, you don't let cold weather keep you off the course. This adidas jacket has you covered when the temperature drops. Down insulation warms your core, and stretch-woven fabric on the arms ensures full range of motion. A stand-up collar provides extra protection, and pockets are there to warm your hands between shots.", "DETAILS", "Regular fit\n- Shell: 86% nylon, 14% elastane dobby with durable water-repellent (DWR) coating on body\n- Fill: 80% duck down, 20% feathers\n- Stretch-woven fabric", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3564313017a3435985b8ad12012de668_9366/Frostguard_Recycled_Content_Full-Zip_Padded_Jacket_Blue_H50984_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/03b8a48dc34645feadbbad120111ca42_9366/Frostguard_Recycled_Content_Full-Zip_Padded_Jacket_Blue_H50984_23_hover_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/95a259312c174dfe9d62ad140005e570_9366/Frostguard_Recycled_Content_Full-Zip_Padded_Jacket_Black_H50986_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/12863237fb854828b674ad18014ab26a_9366/Frostguard_Recycled_Content_Full-Zip_Padded_Jacket_Black_H50986_01_laydown.jpg", 950000);
        handler.add_item("Marimekko Run Icons 3-Stripes Hooded Running Windbreaker", Item.FEMALE, "Jackets" ,  "PRODUCT DESCRIPTION", "AN ADIDAS X MARIMEKKO WINDBREAKER MADE IN PART WITH RECYCLED MATERIALS.\nFinnish brand Marimekko has championed female empowerment since the '50s. And because there's no better place to find your power than on the pavement, this adidas running jacket gives you all the tools, like WIND.RDY that blocks out cold gusts of air, zip pockets and a packable design. Doesn't it feel good to let your feet fly?\nMade with a series of recycled materials, and at least 60% recycled content, this product represents just one of our solutions to help end plastic waste.", "DETAILS", "- Regular fit\n- Full zip with bungee-adjustable hood\n- 88% recycled polyester, 12% elastane ripstop\n- WIND.RDY\n- Reflective details", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/37c94df9e802470cb1d1ae88013a4294_9366/Marimekko_Run_Icons_3-Stripes_Hooded_Running_Windbreaker_Orange_HH7323_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8de01fcdf8d84cf19ed9ae88013a3b56_9366/Marimekko_Run_Icons_3-Stripes_Hooded_Running_Windbreaker_Orange_HH7323_23_hover_model.jpg", 615000);



        // Pants
        // id 48 -> 51
        handler.add_item("Adicolor Contempo Cargo Pants", Item.MALE, "Pants", "PRODUCT DESCRIPTION", "CARGO PANTS FOR CITY EXPLORERS.\n Wait for the adventure? No way. Go find it. Or better yet, go create it. Just pull on these adidas cargo pants for durability, comfort and utilitarian style while you're at it. Ripstop fabric holds up to long days of play, plus multiple pockets give you plenty of storage options.", "DETAILS", "- Loose fit\n- Drawcord on elastic waist\n- 100% nylon ripstop\n- Drawcord-adjustable hems", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/17ea2b50459c42a08d1dae800126807f_9366/Adicolor_Contempo_Cargo_Pants_Black_HK2873_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3ba6eb7992ff4d119011ae8001267838_9366/Adicolor_Contempo_Cargo_Pants_Black_HK2873_23_hover_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/17ea2b50459c42a08d1dae800126807f_9366/Adicolor_Contempo_Cargo_Pants_Black_HK2873_25_model.jpg", 480000);
        handler.add_item("ULTIMATE365 Tapered Pants", Item.MALE, "Pants", "PRODUCT DESCRIPTION", "TAPERED GOLF PANTS MADE WITH RECYCLED MATERIALS.\n For ultimate comfort on any course and any day, these adidas golf pants have you covered. The durable twill fabric is made for year-round play, with a breathable feel and four-way stretch for a full range of motion. Built-in UV coverage lets you play with confidence on sunny days. The tapered cut adds the finishing touch. Made with 100% recycled materials, this product represents just one of our solutions to help end plastic waste.", "DETAILS", "- Regular fit\n- Belt loops with fly\n- 100% recycled polyester twill\n- Breathable four-way stretch fabric", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/23227c9b4e8545bbad43adeb00cc6262_9366/Ultimate365_Tapered_Pants_Black_HA6206_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3c60fff9f86d4daeab7eadf2002413b4_9366/Ultimate365_Tapered_Pants_Blue_HA6205_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/48e3f414fae748258d26ae4a00cc33c3_9366/Ultimate365_Tapered_Pants_Green_HM3230_25_model.jpg", 399000);
        handler.add_item("Studio Lounge Wide Leg Fleece Pants", Item.FEMALE, "Pants", "PRODUCT DESCRIPTION", "COSY, WIDE-LEGGED FLEECE PANTS MADE WITH NATURE.\n You've done it. Checked off the things on your list. Or maybe you're planning to. These loose-fitting, flowing adidas pants are there for it all. Reset, get going and do what you need. The cosy fleece build is super-soft, which means you'll stay comfortable whatever you're doing. These pants are made with natural and renewable materials as part of our journey to design out finite resources and help end plastic waste.", "DETAILS", "- Loose fit\n- Drawcord on elastic waist\n- 50% organic cotton,/30% lyocell, 20% recycled polyester fleece\n- Wide legs in 7/8 length", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d0a2641e43c744f2a823aed6013b4065_9366/Studio_Lounge_Wide_Leg_Fleece_Pants_Blue_HN0691_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e1e9cdfb70bf42119831aeca00fe3eaf_9366/Studio_Lounge_Wide_Leg_Fleece_Pants_White_HM9921_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/393c79f06c00435cb84caeca00fe654a_9366/Studio_Lounge_Wide_Leg_Fleece_Pants_White_HM9921_01_laydown.jpg", 530000);
        handler.add_item("Adicolor Classics Firebird Track Pants", Item.FEMALE, "Pants", "PRODUCT DESCRIPTION", "TRACK PANTS WITH RETRO STYLE, MADE IN PART WITH PARLEY OCEAN PLASTIC.\nClassic Firebird design takes the form of the most comfortable adidas track pants ever. Even better, when you scan the QR code, you'll see every part of the production process from beginning to end. Then there's the details that come in handy, like side pockets and a drawcord on the elastic waist.\nThis garment is made with a yarn which contains 50% Parley Ocean Plastic — reimagined plastic waste, intercepted on remote islands, beaches, coastal communities and shorelines, preventing it from polluting our ocean. This garment contains at least 70% recycled content in total.", "DETAILS", "- Regular fit\n- Drawcord on elastic waist\n- 100% recycled polyester tricot\n- Yarn contains 50% Parley Ocean Plastic\n- This garment contains a minimum of 70% recycled material in total", "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/493003b8e9eb4be58071aefd00ecf7db_9366/Adicolor_Classics_Firebird_Track_Pants_Burgundy_IB7327_25_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e64117a5d28f4977806daefd00ecef59_9366/Adicolor_Classics_Firebird_Track_Pants_Burgundy_IB7327_23_hover_model.jpg<<<https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a8946aecd3cf45668f10aefd00ed1c19_9366/Adicolor_Classics_Firebird_Track_Pants_Burgundy_IB7327_01_laydown.jpg", 299000);

        handler.add_na_item(1);
        handler.add_na_item(6);
        handler.add_na_item(11);
        handler.add_na_item(16);
        handler.add_na_item(25);
        handler.add_na_item(32);
        handler.add_na_item(39);
        handler.add_na_item(43);
        handler.add_na_item(48);


        handler.add_tfm_item(43);
        handler.add_tfm_item(49);
        handler.add_tfm_item(34);
        handler.add_tfm_item(17);
        handler.add_tfm_item(7);
        handler.add_tfm_item(12);

        handler.add_tfw_item(42);
        handler.add_tfw_item(50);
        handler.add_tfw_item(29);
        handler.add_tfw_item(37);
        handler.add_tfw_item(10);
        handler.add_tfw_item(15);

        ArrayList<String> sizes = new ArrayList<String>(Arrays.asList("S", "M", "L", "XL", "XXL", "3XL"));
        ArrayList<String> color = new ArrayList<String>(Arrays.asList("Black", "White", "Be", "Grey"));

        for (int i = 1; i <= 51; i++)
            for (int j = 0; j < sizes.size(); j++)
                for (int k = 0; k < color.size(); k++) {
                    handler.add_quantity(i, sizes.get(j), color.get(k), 10);
                    //Log.d("tag", "i = " + i);
                }

        handler.close_DB();
    }
}
